apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: dsa-test-api
  namespace: prd-api
spec:
  selector:
    matchLabels:
      app: dsa-test-api
  replicas: {{ .Values.api.replicas }} 
  template:
    metadata:
      labels:
        app: dsa-test-api
    spec:
      containers:
      - image: 278330437803.dkr.ecr.ap-northeast-2.amazonaws.com/dsa-test-api:ver33
        imagePullPolicy: Always
        name: dsa-test-api       
        ports:
        - containerPort: 9000
  strategy:
    blueGreen:
      previewService: dsa-test-api-prv
      activeService: dsa-test-api
      autoPromotionEnabled: true
      previewReplicaCount: 1
      scaleDownDelaySeconds: 60
